version: 2
jobs:
    build:
      working_directory: ~/circleci-demo-python-django
      docker:
          - image: circleci/python:3.6.4
      steps:
          - checkout
          - run:
              command: |
                  sudo pip install pipenv
                  pipenv install -r pip-requirements.txt
          - run:
              command: |
                  pipenv run python manage.py test